project:
  type: website
  output-dir: _site

website:
  title: "ethord - Data Removal Notice"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/Global-Health-Engineering/ethord

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
